### ISSUE TITLE
Cannot open the file(Solved)

### ISSUE THREAD

**Issue by paint1210** [MrPifo/DBD-Plus#1]
problem solved, just delete this issued

**Comment by MrPifo** [comment]
Nice to see that you managed to fix it :)
Am 15.06.2020 18:16:09 schrieb paint1210 <notifications@github.com>:
Good day, MrPifo
I had downloaded your file and installed the latest java.
However, when I open the file, only the cmd pop up in the second and closed
Then nothing happened until I reopen and the same thing happened again.
I am noob in this type of staff, is there any link that I can refer regarding this error?
