### ISSUE TITLE
Profile link always NULL

### ISSUE THREAD

**Issue by Robertolw** [MrPifo/DBD-Plus#3]
Old version can get killer Steam profile but the new 1.7 is always NULL

**Comment by MrPifo** [comment]
It's not possible anymore to retrieve the steamid from the logfiles. Feature will be removed in the next version.

**Comment by Robertolw** [comment]
What I mean is the 1.6.2 still detects killer profile correctly for me.

**Comment by MrPifo** [comment]
Wait, really? Sorry, I just wanted to push a fast update, so it's not completely useless :D
Thanks for letting me know

**Comment by Robertolw** [comment]
Sometimes you need to reopen DBD Plus because it gets stuck with same profile. (1.6.2)
