### ISSUE TITLE
File wont open (solved)

### ISSUE THREAD

**Issue by yahevinn** [MrPifo/DBD-Plus#4]
At first everything was fine, it was working. Then the next day after trying to execute it again, it suddenly stopped working. Nothing pops up and nothing happens. I tried everything i could though i cant do much.

**Comment by AlarmeOrphee5** [comment]
Hey, The programm has the same issue
 tried to recompile and run the file from source, but I don't have one of the libraries and can't find it..

**Comment by MrPifo** [comment]
Hey, for me it still works fine and I didn't upload any new updates. Try deleting the saved config files at C:/DBDPLUS and afterwards try to start the program. Otherwise try open it with CMD and execute it there to see if any errors are happening and let me know.
You can execute the .jar in CMD like this:  java -jar "DBD Plus.jar"

**Comment by ghost** [comment]
I have the same problem

**Comment by AlarmeOrphee5** [comment]
Hey MrPifo, it was worked for me, only if the software is on the CMD.

**Comment by MrPifo** [comment]
> 
> 
> Hey MrPifo, it was worked for me, only if the software is on the CMD.

Great! Maybey something got broken with your Java default execution path. That problem may sometimes occure when you install new Java software or updates etc. 
There are tutorials how to add the java execution path to your default system parameters

**Comment by AlarmeOrphee5** [comment]
Yes, but I don't care a bit. I would do a little script to fix it. Great your program :) I would just like to know, the log file of dead by daylight is read on the game server or is it saved on the computer? In short, I do not expect answers. Thank you and see you soon.

**Comment by AlarmeOrphee5** [comment]
The display of the name of the map in the overlay is a bit broken :) but as far as the detection of killers is concerned. beautiful work

**Comment by MrPifo** [comment]
Thanks, I will look into it!

**Comment by yahevinn** [comment]
Hey, sorry for the late response. After trying to run it with CMD i got this:
An error has occurred while processing the shared archive file.
Unable to unmap shared space.
Error occurred during initialization of VM
Unable to use shared archive.

**Comment by yahevinn** [comment]
Hi, its me again. Everything is all right now. I made some mess in my files, reinstalled java a few times and finally installed both versions of it and somehow its working now. Thank you MrPifo for your help! Closing the issue.
